apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mediawiki
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mediawiki
  template:
    metadata:
      labels:
        network/wikinetwork: "true"
        service: mediawiki
    spec:
      containers:
      - image: "{{ .Values.mediawikiapp.image.repository }}:{{ .Values.mediawikiapp.image.tag}}"
        volumeMounts:
          - mountPath: /data/file
            name: file
        imagePullPolicy: Always
        name: mediawiki
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: file
          persistentVolumeClaim:
            claimName: file
